services:
  postgres:
    image: postgres:15
    container_name: macro-clients-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: macro-clients-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - macro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d macro-clients-db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:

networks:
  macro-network:
    driver: bridge