global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus se monitorea a sí mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Microservicio de Clientes MACRO
  - job_name: 'macro-clients-ms'
    static_configs:
      - targets: ['192.168.0.193:3000']  # IP del host para conectar desde Docker
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # PostgreSQL exporter (opcional, si quieres métricas de BD)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']